name: Deploy
environment: production
on: 
  push:
    branches:
      - master
jobs:
  upload_to_host:
    - name: Upload to Host
    - runs-on: ubuntu-latest
    - steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Upload Files to Server using SCP
        uses: appleboy/scp-action@master
        with:
          host: davidreti.net
          username: ${{ secrets.UPLOAD_USERNAME }}
          key: ${{ secrets.UPLOAD_KEY }}
          source: "*" 
          target: ${{ secrets.UPLOAD_PATH }}